
language: python
python: "3.7.5"



install:
  - pip install pytest-cov
  - pip install .
  - pip install -r test_requirements.txt

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - pytest pacco/cli/tests.py --cov=pacco --cov-config=.coveragerc
  - pytest --doctest-modules --cov=pacco --cov-append --cov-config=.coveragerc --cov-report xml
  - coverage report -m

after_script:
  - ./cc-test-reporter format-coverage -t coverage.py
  - ./cc-test-reporter upload-coverage

deploy:
  provider: script
  script: bash scripts/pypi_publish.sh
  on:
    branch: master
